name: Deploy Frontend

on:
  push:
    branches:
      - staging
      - specific_branch
      - master

jobs:
  deploy_qa:
    if: github.ref == 'refs/heads/specific_branch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect with VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p apps/backend && cd apps/backend