name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Hostinger
        uses: https://github.com/keshav9761/Oscars.git
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            mkdir -p ~/work/Oscars
            echo "Deploying to VPS"
            # Navigate to the correct directory
            cd ~/work/Oscars || { echo "Directory not found"; exit 1; }
            # Verify that we're in a Git repository
            if [ ! -d ".git" ]; then
              echo "Not a git repository"; exit 1;
            fi
            # Pull latest changes
            git pull origin master
            git status
            npm install --only=prod
            # Uncomment the following line if you use pm2 to manage processes
            # pm2 restart YoutubeApp
