name: Deploy to Hostinger Using GitHub Actions

on:
  push:
    branches:
      - master # The branch name your are commit the new changes
jobs:
  build_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - run: |
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd domains && ls -l && chmod 777 http://89.116.33.204 && ls -l && cd http://89.116.33.204 && ls -l && rm -rf * && rm -rf .git && rm -rf .github && git clone https://github.com/keshav9761/Oscars.git .'